dinov3_node:
  ros__parameters:
    # General params for image
    img_size: 800
    patch_size: 16
    img_mean: [0.485, 0.456, 0.406]
    img_std: [0.229, 0.224, 0.225]
    device: 'cuda'

    # Params for dino model
    dino_model:
      repo_path : '/dinov3_ros/dinov3'
      model_name: 'dinov3_vits16plus'
      weights_path: '/dinov3_ros/dinov3_toolkit/backbone/weights/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth'
      n_layers: 12
      embed_dim: 384
      source: "local"

    # Params for object detection (od)
    detection_model:
      weights_path: '/dinov3_ros/dinov3_toolkit/head_detection/weights/model_0.pth'
      fpn_ch: 256
      n_convs: 4
      n_classes: 80